### ISSUE TITLE
Are you still using this?

### ISSUE THREAD

**Issue by frenzymadness** [fedora-python/kojistatus#10]
If so, let me know. We need to migrate the CI to new Pythons because the dependencies in setup.py are not locked and some of them no longer support Python 3.4 and 3.5 we have in Travis config.

**Comment by hroncok** [comment]
Yes, I am using this.

**Comment by frenzymadness** [comment]
@befeleme Interested in some CI configuration?

**Comment by befeleme** [comment]
Sure!

**Comment by frenzymadness** [comment]
In general, we need to clean this repository. Currently, CI is using old Pythons and dependencies are specified in multiple files. We need to update them and consolidate them to a single point of truth.
